### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Ktlo/AVLTree#1]
1. Хотелось бы побольше набор тестов
2. В Котлиновской доке про это явно не сказано, но, видимо следует обратиться к Javadoc для `java.util.Map` чтобы правильно реализовать `equals`/`hashCode`.
3. Заворачивать результат во что-то вроде `Ref` - какой-то сомнительный стиль, лучше вынести его в возвращаемое значение (в `Pair`, если результата два)
4. А стандартный `ArrayDeque` не подходит вместо вашего `ArrayRoundQueue`?

**Comment by Ktlo** [comment]
Всё исправлено, кроме третьего пункта. Тут такая ситуация, что пришлось прибегнуть к классу `Ref`. В той альтернативе, что Вы описываете есть два момента, которые мне не нравятся:
1. Красивые конструкции по типу
    ```kotlin
    root = root.insert(…)
    ```
    будут иметь вид
    ```kotlin
    val r = root.insert(…)
    root = r.first
    ```
    это особенно неприятно в конструкции `when`.
2. Также в результате мне придётся вместо одного объекта `Ref` для операций `put()` и `insert()` создавать несколько Pair на каждый спуск в глубину дерева.

**Comment by gagarski** [comment]
Ок, `Ref` пусть остаётся.

С `equals` осталась небольшая проблема у `AVLTreeMapVCollection`. Сейчас он умеет сравниваться с другими коллекциями (в том числе с множествами и списками), а не должен. Об этом явно сказано в [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html). Так надо потому что иначе нарушается симметричность `equals`. Объект вашего класса может быть равен, например `ArrayList`у, а `ArrayList` никогда не может быть равен вашему объекту. ЧТобы это исправить можно добавить проверку на `is` аналогично другим наследникам `AVLTreeMapCollectionBase `

**Comment by Ktlo** [comment]
Исправлено, теперь `AVLTreeMapVCollection` может сравниваться только с объектами этого же класса.
